# NumPy

# Create different types of NumPy arrays (1D, 2D, 3D).

1. Importing NumPy

In [7]:
import numpy as np

2. Creating a 1D Array

In [10]:
import numpy as np  # Import the NumPy library

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])

# Printing the 1D array
print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5]


3. Creating a 2D Array

In [20]:
# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Printing the 2D array
print("\n2D Array:")
print(array_2d)


2D Array:
[[1 2 3]
 [4 5 6]]


4. Creating a 3D Array

In [18]:
# Creating a 3D NumPy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Printing the 3D array
print("\n3D Array:")
print(array_3d)


3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


5. Creating Arrays with Built-in Functions

In [23]:
# Creating a 1D Array with arange()
array_1d_range = np.arange(10)
print("\n1D Array with arange:")
print(array_1d_range)


1D Array with arange:
[0 1 2 3 4 5 6 7 8 9]


In [25]:
# Creating a 2D Array with zeros()
array_2d_zeros = np.zeros((3, 4)) # 3 rows and 4 columns
print("\n2D Array of zeros:")
print(array_2d_zeros)


2D Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
# Creating a 3D Array with ones()
array_3d_ones = np.ones((2, 3, 4))
print("\n3D Array of ones:")
print(array_3d_ones)


3D Array of ones:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


# Perform basic arithmetic operations on arrays.

1. Creating Sample Arrays

In [35]:
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([10, 20, 30, 40, 50])

# Printing the arrays
print("Array A:")
print(array_a)

print("\nArray B:")
print(array_b)

Array A:
[1 2 3 4 5]

Array B:
[10 20 30 40 50]


2. Basic Arithmetic Operations

In [38]:
# Addition
addition = array_a + array_b
print("Addition:")
print(addition)

Addition:
[11 22 33 44 55]


In [40]:
# Subtraction
subtraction = array_b - array_a
print("\nSubtraction:")
print(subtraction)


Subtraction:
[ 9 18 27 36 45]


In [42]:
# Multiplication
multiplication = array_a * array_b
print("\nMultiplication:")
print(multiplication)


Multiplication:
[ 10  40  90 160 250]


In [44]:
# Division
division = array_b / array_a
print("\nDivision:")
print(division)


Division:
[10. 10. 10. 10. 10.]


3. Operations on 2D Arrays

In [51]:
# create
array_2d_a = np.array([[1, 2], [3, 4]])
array_2d_b = np.array([[10, 20], [30, 40]])

# Printing the arrays
print("Array A:")
print(array_a)

print("\nArray B:")
print(array_b)

Array A:
[1 2 3 4 5]

Array B:
[10 20 30 40 50]


In [53]:
# Addition
addition_2d = array_2d_a + array_2d_b
print("\n2D Addition:")
print(addition_2d)


2D Addition:
[[11 22]
 [33 44]]


In [55]:
# Subtraction
subtraction_2d = array_2d_b - array_2d_a
print("\n2D Subtraction:")
print(subtraction_2d)


2D Subtraction:
[[ 9 18]
 [27 36]]


In [57]:
# Multiplication
multiplication_2d = array_2d_a * array_2d_b
print("\n2D Multiplication:")
print(multiplication_2d)


2D Multiplication:
[[ 10  40]
 [ 90 160]]


In [59]:
# Division
division_2d = array_2d_b / array_2d_a
print("\n2D Division:")
print(division_2d)


2D Division:
[[10. 10.]
 [10. 10.]]


4. Scalar Operations

In [61]:
# Scalar addition
scalar_add = array_a + 5
print("\nScalar Addition:")
print(scalar_add) # Output: [ 6 7 8 9 10]

# Scalar multiplication
scalar_multiply = array_2d_a * 2
print("\nScalar Multiplication:")
print(scalar_multiply)


Scalar Addition:
[ 6  7  8  9 10]

Scalar Multiplication:
[[2 4]
 [6 8]]


# Use indexing and slicing to access elements.

1. Indexing in 1D Arrays

In [67]:
# Creating a sample Array
array_1d = np.array([10, 20, 30, 40, 50])

first_element = array_1d[0]
print("\nFirst Element:", first_element)
last_element = array_1d[-1]
print("Last Element:", last_element)


First Element: 10
Last Element: 50


2. Slicing in 1D Arrays

In [70]:
# Slicing from index 1 to 3 (exclusive of 3)
slice_1d = array_1d[1:4]
print("\nSliced Array (from index 1 to 3):", slice_1d)

# Slicing with step
slice_step = array_1d[::2]
print("Sliced Array with Step 2:", slice_step)


Sliced Array (from index 1 to 3): [20 30 40]
Sliced Array with Step 2: [10 30 50]


3. Indexing in 2D Arrays

In [72]:
# Creating a 2D Array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing the element in the second row and second column
element_2d = array_2d[1, 1]
print("\nElement at (1, 1):", element_2d)

# Accessing the element in the third row and first column
element_3rd_row = array_2d[2, 0]
print("Element at (2, 0):", element_3rd_row)


Element at (1, 1): 5
Element at (2, 0): 7


4. Slicing in 2D Array

In [85]:
# Slicing the first two rows of the 2D array
slice_rows = array_2d[0:2]

# Printing the sliced rows
print("\nSliced Rows (first two):")
print(slice_rows)


Sliced Rows (first two):
[[1 2 3]
 [4 5 6]]


In [81]:
# Slicing the first column
slice_column = array_2d[:, 0]

# Printing the sliced column
print("\nSliced Column (first column):", slice_column)


Sliced Column (first column): [1 4 7]


In [83]:
# Slicing a Submatrix
submatrix = array_2d[0:2, 0:2]

# Printing the sliced Submatrix
print("\nSliced Submatrix (first two rows and columns):")
print(submatrix)


Sliced Submatrix (first two rows and columns):
[[1 2]
 [4 5]]


# Explore array manipulation functions (reshape, transpose, concatenate).

1. Reshape

In [88]:
# Creating a Sample Array
array_1d = np.array([1, 2, 3, 4, 5, 6])

#Reshape to 2D
array_2d = array_1d.reshape((2, 3))
print("\nReshaped to 2D Array (2x3):")
print(array_2d)


Reshaped to 2D Array (2x3):
[[1 2 3]
 [4 5 6]]


In [93]:
# Reshape to 3D
array_3d = array_1d.reshape((1, 2, 3))
print("\nReshaped to 3D Array (1x2x3):")
print(array_3d)


Reshaped to 3D Array (1x2x3):
[[[1 2 3]
  [4 5 6]]]


2. Transpose

In [96]:
# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Transposing the 2D array
transposed_array = array_2d.T

# Printing the transposed 2D array
print("\nTransposed 2D Array:")
print(transposed_array)


Transposed 2D Array:
[[1 4]
 [2 5]
 [3 6]]


In [98]:
# Creating a 3D NumPy array
array_3d = np.array([[[1, 2], [3, 4]], 
                      [[5, 6], [7, 8]]])

# Printing the original 3D array
print("Original 3D Array:")
print(array_3d)

# Transposing the 3D array
transposed_3d = np.transpose(array_3d, axes=(1, 0, 2))  # Change the order of axes

# Printing the transposed 3D array
print("\nTransposed 3D Array (axes reordered):")
print(transposed_3d)

Original 3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Transposed 3D Array (axes reordered):
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


3. Concatenate

In [101]:
# Concatenate 1D Arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

# Concatenating along the first axis (default)
concatenated_1d = np.concatenate((array_a, array_b))
print("\nConcatenated 1D Array:")
print(concatenated_1d)


Concatenated 1D Array:
[1 2 3 4 5 6]


In [106]:
# Creating two 2D arrays
array_2d_a = np.array([[1, 2, 3], [4, 5, 6]])
array_2d_b = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenating along rows (axis 0)
concatenated_2d_rows = np.concatenate((array_2d_a, array_2d_b), axis=0)
print("\nConcatenated 2D Array (along rows):")
print(concatenated_2d_rows)

# Concatenating along columns (axis 1)
concatenated_2d_cols = np.concatenate((array_2d_a, array_2d_b), axis=1)
print("\nConcatenated 2D Array (along columns):")
print(concatenated_2d_cols)


Concatenated 2D Array (along rows):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated 2D Array (along columns):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Create and use NumPy random number generators.

1. Creating Random Number Generators

In [109]:
rng = np.random.default_rng()

2. Generating Random Numbers

In [112]:
# Generating 5 random floats
random_floats = rng.random(5)

print("Random Floats:")
print(random_floats)

Random Floats:
[0.68978903 0.47509682 0.6658086  0.03225646 0.85361639]


In [114]:
# Generating 5 random integers between 0 and 10 (exclusive)
random_integers = rng.integers(low=0, high=10, size=5)

print("\nRandom Integers:")
print(random_integers)


Random Integers:
[9 1 3 4 4]


3. Generating Random Samples from a Normal Distribution

In [124]:
# Create a random number generator
rng = np.random.default_rng()

# Generate random samples from a normal distribution
normal_samples = rng.normal(loc=0.0, scale=1.0, size=5)

# Printing the random samples
print("\nRandom Samples from Normal Distribution:")
print(normal_samples)


Random Samples from Normal Distribution:
[0.53029107 0.54785792 0.7279842  1.00121169 0.15637181]


4. Generating Random Samples from a Uniform Distribution

In [122]:
# Create a random number generator
rng = np.random.default_rng()

# Generate random samples from a uniform distribution
uniform_samples = rng.uniform(low=1.0, high=10.0, size=5)

# Printing the random samples
print("\nRandom Samples from Uniform Distribution:")
print(uniform_samples)


Random Samples from Uniform Distribution:
[9.69294676 6.43748378 1.20964323 5.50671193 1.77677182]
